2024-04-02 20:15:14,116 | INFO | test_login.py: 25|------开始执行测试用例，开始时间为：2024-04-02 20:15:14------
2024-04-02 20:15:14,117 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-02 20:15:14,117 | INFO | test_login.py: 71|***正在执行正常登录用例***
2024-04-02 20:15:14,117 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-02 20:15:14,117 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-02 20:15:14,117 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-02 20:15:14,117 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010.com'}
2024-04-02 20:15:14,251 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-02 20:15:14,252 | INFO | requests_utils.py: 24|响应success为：True
2024-04-02 20:15:14,252 | INFO | requests_utils.py: 25|响应message为：登录成功
2024-04-02 20:15:14,253 | INFO | test_login.py: 73|用例执行成功，请求的结果为：{'success': True, 'message': '登录成功', 'code': 200, 'result': {'multi_depart': 0, 'userInfo': {'id': 'e9ca23d68d884d4ebb19d07889727dae', 'username': 'admin', 'realname': '管理员', 'password': 'a2aa542a6313470b', 'salt': 'MT8T61Hf', 'avatar': 'user/20190119/logo-2_1547868176839.png', 'birthday': '2018-12-05', 'sex': 1, 'email': '11@qq.com', 'phone': '18566666661', 'orgCode': 'A01', 'status': 1, 'delFlag': '0', 'createBy': None, 'createTime': '2038-06-21 17:54:10', 'updateBy': 'admin', 'updateTime': '2024-03-22 17:10:37', 'activitiSync': '0'}, 'departs': [], 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTIwNjczMTMsInVzZXJuYW1lIjoiYWRtaW4ifQ.tBrYXTQO14KU_Bb_kYIabQuk8RtTXkfgDm9Jt7QeqR4'}, 'resultList': None, 'timestamp': 1712060113415}
2024-04-02 20:15:14,253 | INFO | test_login.py: 88|用例断言成功
2024-04-02 20:15:14,313 | INFO | mysql.py: 28|执行sql语句成功！
2024-04-02 20:15:14,319 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-02 20:15:14,319 | INFO | test_login.py: 71|***正在执行密码错误用例***
2024-04-02 20:15:14,319 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-02 20:15:14,319 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-02 20:15:14,319 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-02 20:15:14,319 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010'}
2024-04-02 20:15:14,376 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-02 20:15:14,377 | INFO | requests_utils.py: 24|响应success为：False
2024-04-02 20:15:14,377 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-02 20:15:14,377 | INFO | test_login.py: 73|用例执行成功，请求的结果为：{'success': False, 'message': '用户名或密码错误', 'code': 500, 'result': None, 'resultList': None, 'timestamp': 1712060113605}
2024-04-02 20:15:14,378 | INFO | test_login.py: 88|用例断言成功
2024-04-02 20:15:14,464 | INFO | mysql.py: 28|执行sql语句成功！
2024-04-02 20:15:14,470 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-04-02 20:15:14,470 | INFO | test_login.py: 71|***正在执行密码为空用例***
2024-04-02 20:15:14,470 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-04-02 20:15:14,470 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-04-02 20:15:14,470 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-04-02 20:15:14,470 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': ''}
2024-04-02 20:15:14,535 | INFO | requests_utils.py: 23|响应状态码为：200
2024-04-02 20:15:14,536 | INFO | requests_utils.py: 24|响应success为：False
2024-04-02 20:15:14,536 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-04-02 20:15:14,536 | INFO | test_login.py: 73|用例执行成功，请求的结果为：{'success': False, 'message': '用户名或密码错误', 'code': 500, 'result': None, 'resultList': None, 'timestamp': 1712060113764}
2024-04-02 20:15:14,537 | INFO | test_login.py: 88|用例断言成功
2024-04-02 20:15:14,580 | INFO | mysql.py: 28|执行sql语句成功！
2024-04-02 20:15:14,584 | INFO | test_login.py: 28|------执行测试结束，完成时间为：2024-04-02 20:15:14------
