2024-03-31 20:59:30,352 | INFO | test_login.py: 21|------开始执行测试用例，开始时间为：2024-03-31 20:59:30------
2024-03-31 20:59:30,353 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-03-31 20:59:30,353 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-03-31 20:59:30,353 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-03-31 20:59:30,353 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-03-31 20:59:30,354 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010.com'}
2024-03-31 20:59:32,570 | INFO | requests_utils.py: 23|响应状态码为：200
2024-03-31 20:59:32,571 | INFO | requests_utils.py: 24|响应success为：True
2024-03-31 20:59:32,571 | INFO | requests_utils.py: 25|响应message为：登录成功
2024-03-31 20:59:32,574 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-03-31 20:59:32,574 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-03-31 20:59:32,574 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-03-31 20:59:32,575 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-03-31 20:59:32,575 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '10010'}
2024-03-31 20:59:32,621 | INFO | requests_utils.py: 23|响应状态码为：200
2024-03-31 20:59:32,622 | INFO | requests_utils.py: 24|响应success为：False
2024-03-31 20:59:32,622 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-03-31 20:59:32,626 | INFO | mysql.py: 15|数据库查询结果为：{'id': 1, 'web': '急救云', 'key': 'url_api', 'value': 'http://systest.whsaviour.com/platform-admin'}
2024-03-31 20:59:32,626 | INFO | requests_utils.py: 7|发送请求的url为：http://systest.whsaviour.com/platform-admin/sys/login
2024-03-31 20:59:32,626 | INFO | requests_utils.py: 8|发送请求的method为：post
2024-03-31 20:59:32,626 | INFO | requests_utils.py: 9|发送请求的headers为：{'Content-Type': 'application/json'}
2024-03-31 20:59:32,626 | INFO | requests_utils.py: 10|发送请求的data为：{'username': 'admin', 'password': '1'}
2024-03-31 20:59:32,667 | INFO | requests_utils.py: 23|响应状态码为：200
2024-03-31 20:59:32,668 | INFO | requests_utils.py: 24|响应success为：False
2024-03-31 20:59:32,668 | INFO | requests_utils.py: 25|响应message为：用户名或密码错误
2024-03-31 20:59:32,671 | INFO | test_login.py: 24|------执行测试结束，完成时间为：2024-03-31 20:59:30------
